### ISSUE TITLE
set num_tokens to the number of active tokens

### ISSUE THREAD

**Issue by kolinko** [trivial-co/trivial#36]
it seems we don't set num_tokens public property of ERC20token in our contract?

**Comment by Mc01** [comment]
In ERC20 there is`totalSupply` and it equals to `tokensForArtist` + `tokensForTrivial` + `tokensForIco`

And all of them are public

**Comment by kolinko** [comment]
Where are we setting the totalSupply? I couldn't find a line that sets it to the proper amount anywhere in the code...

**Comment by Mc01** [comment]
Here: https://github.com/trivial-co/trivial/blob/master/contracts/TrivialToken.sol#L141
